### ISSUE TITLE
HEST installation on Windows fails with missing wheel error

### ISSUE THREAD

**Issue by adiv5** [mahmoodlab/HEST#72]
following the instructions for installation as mentioned, getting the following error while installing Additional dependencies (GPU acceleration):

```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu12==24.6.*
  Using cached cudf_cu12-24.6.1.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.6.1-cp310-cp310-manylinux_2_28_aarch64.whl against tag cp310-cp310-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.6.1-cp310-cp310-manylinux_2_28_x86_64.whl against tag cp310-cp310-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.6.1-cp311-cp311-manylinux_2_28_aarch64.whl against tag cp311-cp311-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.6.1-cp311-cp311-manylinux_2_28_x86_64.whl against tag cp311-cp311-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.6.1-cp39-cp39-manylinux_2_28_aarch64.whl against tag cp39-cp39-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.6.1-cp39-cp39-manylinux_2_28_x86_64.whl against tag cp39-cp39-manylinux_2_28_x86_64
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for cudf-cu12 24.6.1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\E87205\AppData\Local\miniconda3\envs\hest\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\E87205\AppData\Local\miniconda3\envs\hest\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\E87205\AppData\Local\miniconda3\envs\hest\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 179, in download_wheel
          report_install_failure(distribution, version, exception_context)
        File "C:\Users\E87205\AppData\Local\Temp\pip-build-env-qgmmmu2q\overlay\Lib\site-packages\nvidia_stub\error.py", line 63, in report_install_failure
          raise InstallFailedError(
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************

      The installation of cudf-cu12 for version 24.6.1 failed.

      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.

      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cudf-cu12
      ```

      Here is some debug information about your platform to include in any bug
      report:

      Python Version: CPython 3.9.20
      Operating System: Windows 10
      CPU Architecture: AMD64
      Driver Version: 556.12
      CUDA Version: 12.5

      *******************************************************************************

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

A simple solution is to install using recommended command, thus losing out on the version specified and installing older version. 

is there an alternate solution to this

**Comment by pauldoucet** [comment]
Hi @adiv5,
Cucim for Windows isn't available on PyPI yet. You can try following the manual installation steps described [here](https://github.com/rapidsai/cucim/issues/86). However, please note that the HEST library will still work even if you don't have Cucim installed; it will default to using OpenSlide instead.

**Comment by adiv5** [comment]
Thanks @pauldoucet.
